services:
  org-shell-cmd:
    image: alpine
    networks:
      - hl-fabric
  org1-ca-tls:
    image: hyperledger/fabric-ca:${FABRIC_CA_VERSION}
    # ports:
    #   - <PORT>:7054
    networks:
      - hl-fabric
  org1-ca-identities:
    image: hyperledger/fabric-ca:${FABRIC_CA_VERSION}
    # ports:
    #   - <PORT>:7054
    networks:
      - hl-fabric
  org2-ca-tls:
    image: hyperledger/fabric-ca:${FABRIC_CA_VERSION}
    # ports:
    #   - <PORT>:7054
    networks:
      - hl-fabric
  org2-ca-identities:
    image: hyperledger/fabric-ca:${FABRIC_CA_VERSION}
    # ports:
    #   - <PORT>:7054
    networks:
      - hl-fabric
  org3-ca-tls:
    image: hyperledger/fabric-ca:${FABRIC_CA_VERSION}
    # ports:
    #   - <PORT>:7054
    networks:
      - hl-fabric
  org3-ca-identities:
    image: hyperledger/fabric-ca:${FABRIC_CA_VERSION}
    # ports:
    #   - <PORT>:7054
    networks:
      - hl-fabric  
  org2-peer1:
    image: hyperledger/fabric-peer:${FABRIC_PEER_VERSION}
    # ports:
    #   - <PORT>:7051
    networks:
      - hl-fabric
  org2-peer2:
    image: hyperledger/fabric-peer:${FABRIC_PEER_VERSION}
    # ports:
    #   - <PORT>:7051
    networks:
      - hl-fabric
  org3-peer1:
    image: hyperledger/fabric-peer:${FABRIC_PEER_VERSION}
    # ports:
    #   - <PORT>:7051
    networks:
      - hl-fabric
  org3-peer2:
    image: hyperledger/fabric-peer:${FABRIC_PEER_VERSION}
    # ports:
    #   - <PORT>:7051
    networks:
      - hl-fabric
  org3-peer3:
    image: hyperledger/fabric-peer:${FABRIC_PEER_VERSION}
    # ports:
    #   - <PORT>:7051
    networks:
      - hl-fabric
  org2-cli-peer1:
    image: hyperledger/fabric-tools:${FABRIC_TOOLS_VERSION}
    networks:
      - hl-fabric
  org3-cli-peer1:
    image: hyperledger/fabric-tools:${FABRIC_TOOLS_VERSION}
    networks:
      - hl-fabric
  org1-orderer1:
    image: hyperledger/fabric-orderer:${PEER_ORDERER_VERSION}
    # ports:
    #   - <PORT>:7050
    networks:
      - hl-fabric
  org1-orderer2:
    image: hyperledger/fabric-orderer:${PEER_ORDERER_VERSION}
    # ports:
    #   - <PORT>:7050
    networks:
      - hl-fabric
  org1-orderer3:
    image: hyperledger/fabric-orderer:${PEER_ORDERER_VERSION}
    # ports:
    #   - <PORT>:7050
    networks:
      - hl-fabric
  orderers-proxy:
    image: nginx-hl-fabric 
    # ports:
    #   - <PORT>:8443
    networks:
      - hl-fabric
  org2-peers-proxy:
    image: nginx-hl-fabric
    # ports:
    #   - <PORT>:8443
    networks:
      - hl-fabric
  org3-peers-proxy:
    image: nginx-hl-fabric
    # ports:
    #   - <PORT>:8443
    networks:
      - hl-fabric
  org2-orderer1:
    image: hyperledger/fabric-orderer:${PEER_ORDERER_VERSION}
    # ports:
    #   - <PORT>:7050
    networks:
      - hl-fabric
  org2-orderer2:
    image: hyperledger/fabric-orderer:${PEER_ORDERER_VERSION}
    # ports:
    #   - <PORT>:7050
    networks:
      - hl-fabric