services:
  org-shell-cmd:
    image: alpine
    networks:
      - hl-fabric
  org1-ca-tls:
    image: nginx-hl-fabric
    #ports:
    #  - 9000:9000
    networks:
      - hl-fabric
  org1-ca-identities:
    image: nginx-hl-fabric
    #ports:
    #  - 9001:9001
    networks:
      - hl-fabric
  org2-ca-tls:
    image: hyperledger/fabric-ca:${FABRIC_CA_VERSION}
    # ports:
    #   - <PORT>:7054
    networks:
      - hl-fabric
  org2-ca-identities:
    image: hyperledger/fabric-ca:${FABRIC_CA_VERSION}
    # ports:
    #   - <PORT>:7054
    networks:
      - hl-fabric
  org3-ca-tls:
    image: hyperledger/fabric-ca:${FABRIC_CA_VERSION}
    # ports:
    #   - <PORT>:7054
    networks:
      - hl-fabric
  org3-ca-identities:
    image: hyperledger/fabric-ca:${FABRIC_CA_VERSION}
    # ports:
    #   - <PORT>:7054
    networks:
      - hl-fabric
  org2-peer1:
    image: hyperledger/fabric-peer:${FABRIC_PEER_VERSION}
    # ports:
    #   - <PORT>:7051
    networks:
      - hl-fabric
  org2-peer2:
    image: hyperledger/fabric-peer:${FABRIC_PEER_VERSION}
    # ports:
    #   - <PORT>:7051
    networks:
      - hl-fabric
  org3-peer1:
    image: hyperledger/fabric-peer:${FABRIC_PEER_VERSION}
    # ports:
    #   - <PORT>:7051
    networks:
      - hl-fabric
  org3-peer2:
    image: hyperledger/fabric-peer:${FABRIC_PEER_VERSION}
    # ports:
    #   - <PORT>:7051
    networks:
      - hl-fabric
  org2-cli-peer1:
    image: hyperledger/fabric-tools:${FABRIC_TOOLS_VERSION}
    networks:
      - hl-fabric
  org3-cli-peer1:
    image: hyperledger/fabric-tools:${FABRIC_TOOLS_VERSION}
    networks:
      - hl-fabric
  org1-orderer1:
    image: hyperledger/fabric-orderer:${PEER_ORDERER_VERSION}
    # ports:
    #   - <PORT>:7050
    networks:
      - hl-fabric
  org1-orderer2:
    image: hyperledger/fabric-orderer:${PEER_ORDERER_VERSION}
    # ports:
    #   - <PORT>:7050
    networks:
      - hl-fabric
  org1-orderer3:
    image: hyperledger/fabric-orderer:${PEER_ORDERER_VERSION}
    # ports:
    #   - <PORT>:7050
    networks:
      - hl-fabric
  org1-ca-db:
    image: postgres
    #ports:
    #  - <PORT>:5432
    networks:
      - hl-fabric
  org1-ca-tls-n0:
    image: hyperledger/fabric-ca:${FABRIC_CA_VERSION}
    #ports:
    # - <PORT>:9000
    networks:
      - hl-fabric
  org1-ca-tls-n1:
    image: hyperledger/fabric-ca:${FABRIC_CA_VERSION}
    #Ports:
    # - <PORT>:9000
    networks:
      - hl-fabric
  org1-ca-identities-n0:
    image: hyperledger/fabric-ca:${FABRIC_CA_VERSION}
    #Ports:
    # - <PORT>:9000
    networks:
      - hl-fabric
  org1-ca-identities-n1:
    image: hyperledger/fabric-ca:${FABRIC_CA_VERSION}
    #ports:
    # - <PORT>:9000
    networks:
      - hl-fabric
